### ISSUE TITLE
Request: documentation for this action?

### ISSUE THREAD

**Issue by DilumAluthge** [julia-actions/julia-processcoverage#1]
If I understand correctly, the plan is that we will deprecate/archive https://github.com/julia-actions/julia-uploadcodecov/issues/1, and instead use this action in combination with https://github.com/codecov/codecov-action.

Is that correct? If so, we need to add some documentation for this action.

cc: @davidanthoff

**Comment by DilumAluthge** [comment]
@davidanthoff Can I assign this to you?

**Comment by SaschaMann** [comment]
Perhaps we could just point all of the `julia-*` READMEs to PkgButler and PkgTemplates?

**Comment by DilumAluthge** [comment]
> Perhaps we could just point all of the `julia-*` READMEs to PkgButler and PkgTemplates?

Well, PkgTemplates doesn't really explain how to use the actions. It just has templates for some of the actions. Also, I don't think it has templates for all of the actions.

And while I like both PkgButler and PkgTemplates, I don't want people to get the impression that their use is mandatory. We should have at least some minimal documentation for all of our active actions. (And we should archive our inactive actions.)

**Comment by davidanthoff** [comment]
Yes, the idea is that you use this action to prepare the coverage files, and then use the official codecov-action for upload. Benefit is that you don't need a token anymore.

Realistically I won't have time to write docs anytime soon, I'm afraid...

**Comment by aminya** [comment]
I want to use this but there is no documentation. Any help?

**Comment by DilumAluthge** [comment]
Right now, the best approach will be to use PkgTemplates. It will automatically set up this Action for you.

**Comment by aminya** [comment]
I just copy-pasted the template from PkgTemplates in #5 

https://github.com/invenia/PkgTemplates.jl/blob/97a062fd4fb798e1172149843d7098e5ec3ba619/templates/github/workflows/ci.yml#L53-L57

Just **as a kind note**: Writing a library probably takes hours of effort. But by not adding a basic readme on how to use it, which could take 2 min, you kinda waste the time you put into writing the library.
